/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalPrivacyPolicyRouteImport } from './routes/legal.privacy-policy'
import { Route as LegalPersonalDataRouteImport } from './routes/legal.personal-data'
import { Route as LegalOfertaRouteImport } from './routes/legal.oferta'
import { Route as LegalMarketingConsentRouteImport } from './routes/legal.marketing-consent'

const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyPolicyRoute = LegalPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPersonalDataRoute = LegalPersonalDataRouteImport.update({
  id: '/personal-data',
  path: '/personal-data',
  getParentRoute: () => LegalRoute,
} as any)
const LegalOfertaRoute = LegalOfertaRouteImport.update({
  id: '/oferta',
  path: '/oferta',
  getParentRoute: () => LegalRoute,
} as any)
const LegalMarketingConsentRoute = LegalMarketingConsentRouteImport.update({
  id: '/marketing-consent',
  path: '/marketing-consent',
  getParentRoute: () => LegalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/legal': typeof LegalRouteWithChildren
  '/legal/marketing-consent': typeof LegalMarketingConsentRoute
  '/legal/oferta': typeof LegalOfertaRoute
  '/legal/personal-data': typeof LegalPersonalDataRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/legal': typeof LegalRouteWithChildren
  '/legal/marketing-consent': typeof LegalMarketingConsentRoute
  '/legal/oferta': typeof LegalOfertaRoute
  '/legal/personal-data': typeof LegalPersonalDataRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/legal': typeof LegalRouteWithChildren
  '/legal/marketing-consent': typeof LegalMarketingConsentRoute
  '/legal/oferta': typeof LegalOfertaRoute
  '/legal/personal-data': typeof LegalPersonalDataRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/legal'
    | '/legal/marketing-consent'
    | '/legal/oferta'
    | '/legal/personal-data'
    | '/legal/privacy-policy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/legal'
    | '/legal/marketing-consent'
    | '/legal/oferta'
    | '/legal/personal-data'
    | '/legal/privacy-policy'
  id:
    | '__root__'
    | '/'
    | '/legal'
    | '/legal/marketing-consent'
    | '/legal/oferta'
    | '/legal/personal-data'
    | '/legal/privacy-policy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LegalRoute: typeof LegalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy-policy': {
      id: '/legal/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/personal-data': {
      id: '/legal/personal-data'
      path: '/personal-data'
      fullPath: '/legal/personal-data'
      preLoaderRoute: typeof LegalPersonalDataRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/oferta': {
      id: '/legal/oferta'
      path: '/oferta'
      fullPath: '/legal/oferta'
      preLoaderRoute: typeof LegalOfertaRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/marketing-consent': {
      id: '/legal/marketing-consent'
      path: '/marketing-consent'
      fullPath: '/legal/marketing-consent'
      preLoaderRoute: typeof LegalMarketingConsentRouteImport
      parentRoute: typeof LegalRoute
    }
  }
}

interface LegalRouteChildren {
  LegalMarketingConsentRoute: typeof LegalMarketingConsentRoute
  LegalOfertaRoute: typeof LegalOfertaRoute
  LegalPersonalDataRoute: typeof LegalPersonalDataRoute
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalMarketingConsentRoute: LegalMarketingConsentRoute,
  LegalOfertaRoute: LegalOfertaRoute,
  LegalPersonalDataRoute: LegalPersonalDataRoute,
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LegalRoute: LegalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
